name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
    paths:
    - "web-app/**"
    - ".firebaserc"
    - "firebase.json"
    - ".github/workflows/firebase-hosting.yml"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-app
    steps:
      - uses: actions/checkout@v3
      - run: |
          touch .env
          echo NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }} >> .env
          echo NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }} >> .env
          echo NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }} >> .env
          echo NEXT_PUBLIC_FIREBASE_APP_URL=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_URL }} >> .env
          cat .env
      - run: npm install
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AISDC_2023 }}'
          channelId: live
          projectId: aisdc-2023
