name: Deploy to Firebase Hosting on push to master
on:
  push:
    branches:
      - main
    paths:
      - "web-app/**"
      - ".firebaserc"
      - "firebase.json"
      - ".github/workflows/firebase-hosting.yml"
jobs:
  staging-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-app
    # TODO: Fill in environment variables once set up
    # env:
    #   KEY: '${{ VALUE }}'
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: aisdc-2023
          channelId: live