name: Deploy to Firebase Function on push to master
on:
  push:
    branches:
      - main
    paths:
      - "functions/**"
      - ".firebaserc"
      - "firebase.json"
      - ".github/workflows/firebase-function.yml"
      - "firestore.rules"
jobs:
  staging-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions
    # TODO: Fill in environment variables once set up
    # env:
    #   KEY: '${{ VALUE }}'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install
      - name: Create SA key
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/gcloud.json
      - name: Deploy Cloud Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions,firestore:rules
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AISDC_2023 }}
